// Generated by rstantools.  Do not edit by hand.

/*
    hdbayes is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    hdbayes is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with hdbayes.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_lm_npp_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_lm_npp");
    reader.add_event(55, 53, "end", "model_lm_npp");
    return reader;
}
#include <stan_meta_header.hpp>
class model_lm_npp
  : public stan::model::model_base_crtp<model_lm_npp> {
private:
        int n;
        int n0;
        int p;
        vector_d y;
        matrix_d X;
        vector_d y0;
        matrix_d X0;
        vector_d mean_beta;
        matrix_d cov_beta;
        double sigmasq_shape;
        double sigmasq_scale;
        double a0_shape1;
        double a0_shape2;
        vector_d offset;
        vector_d offset0;
        vector_d y_offset;
        vector_d y0_offset;
        matrix_d hist_prec;
        vector_d hist_mle;
        matrix_d prior_prec;
        vector_d hist_prec_mle;
        vector_d prior_prec_mean;
        double sumy0sq;
        double quad_b0;
public:
    model_lm_npp(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_lm_npp(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_lm_npp_namespace::model_lm_npp";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 3;
            context__.validate_dims("data initialization", "n", "int", context__.to_vec());
            n = int(0);
            vals_i__ = context__.vals_i("n");
            pos__ = 0;
            n = vals_i__[pos__++];
            check_greater_or_equal(function__, "n", n, 0);
            current_statement_begin__ = 4;
            context__.validate_dims("data initialization", "n0", "int", context__.to_vec());
            n0 = int(0);
            vals_i__ = context__.vals_i("n0");
            pos__ = 0;
            n0 = vals_i__[pos__++];
            check_greater_or_equal(function__, "n0", n0, 0);
            current_statement_begin__ = 5;
            context__.validate_dims("data initialization", "p", "int", context__.to_vec());
            p = int(0);
            vals_i__ = context__.vals_i("p");
            pos__ = 0;
            p = vals_i__[pos__++];
            check_greater_or_equal(function__, "p", p, 0);
            current_statement_begin__ = 6;
            validate_non_negative_index("y", "n", n);
            context__.validate_dims("data initialization", "y", "vector_d", context__.to_vec(n));
            y = Eigen::Matrix<double, Eigen::Dynamic, 1>(n);
            vals_r__ = context__.vals_r("y");
            pos__ = 0;
            size_t y_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < y_j_1_max__; ++j_1__) {
                y(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 7;
            validate_non_negative_index("X", "n", n);
            validate_non_negative_index("X", "p", p);
            context__.validate_dims("data initialization", "X", "matrix_d", context__.to_vec(n,p));
            X = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(n, p);
            vals_r__ = context__.vals_r("X");
            pos__ = 0;
            size_t X_j_2_max__ = p;
            size_t X_j_1_max__ = n;
            for (size_t j_2__ = 0; j_2__ < X_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < X_j_1_max__; ++j_1__) {
                    X(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 8;
            validate_non_negative_index("y0", "n0", n0);
            context__.validate_dims("data initialization", "y0", "vector_d", context__.to_vec(n0));
            y0 = Eigen::Matrix<double, Eigen::Dynamic, 1>(n0);
            vals_r__ = context__.vals_r("y0");
            pos__ = 0;
            size_t y0_j_1_max__ = n0;
            for (size_t j_1__ = 0; j_1__ < y0_j_1_max__; ++j_1__) {
                y0(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 9;
            validate_non_negative_index("X0", "n0", n0);
            validate_non_negative_index("X0", "p", p);
            context__.validate_dims("data initialization", "X0", "matrix_d", context__.to_vec(n0,p));
            X0 = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(n0, p);
            vals_r__ = context__.vals_r("X0");
            pos__ = 0;
            size_t X0_j_2_max__ = p;
            size_t X0_j_1_max__ = n0;
            for (size_t j_2__ = 0; j_2__ < X0_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < X0_j_1_max__; ++j_1__) {
                    X0(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 10;
            validate_non_negative_index("mean_beta", "p", p);
            context__.validate_dims("data initialization", "mean_beta", "vector_d", context__.to_vec(p));
            mean_beta = Eigen::Matrix<double, Eigen::Dynamic, 1>(p);
            vals_r__ = context__.vals_r("mean_beta");
            pos__ = 0;
            size_t mean_beta_j_1_max__ = p;
            for (size_t j_1__ = 0; j_1__ < mean_beta_j_1_max__; ++j_1__) {
                mean_beta(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 11;
            validate_non_negative_index("cov_beta", "p", p);
            validate_non_negative_index("cov_beta", "p", p);
            context__.validate_dims("data initialization", "cov_beta", "matrix_d", context__.to_vec(p,p));
            cov_beta = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(p, p);
            vals_r__ = context__.vals_r("cov_beta");
            pos__ = 0;
            size_t cov_beta_j_2_max__ = p;
            size_t cov_beta_j_1_max__ = p;
            for (size_t j_2__ = 0; j_2__ < cov_beta_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < cov_beta_j_1_max__; ++j_1__) {
                    cov_beta(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            stan::math::check_cov_matrix(function__, "cov_beta", cov_beta);
            current_statement_begin__ = 12;
            context__.validate_dims("data initialization", "sigmasq_shape", "double", context__.to_vec());
            sigmasq_shape = double(0);
            vals_r__ = context__.vals_r("sigmasq_shape");
            pos__ = 0;
            sigmasq_shape = vals_r__[pos__++];
            check_greater_or_equal(function__, "sigmasq_shape", sigmasq_shape, 0);
            current_statement_begin__ = 13;
            context__.validate_dims("data initialization", "sigmasq_scale", "double", context__.to_vec());
            sigmasq_scale = double(0);
            vals_r__ = context__.vals_r("sigmasq_scale");
            pos__ = 0;
            sigmasq_scale = vals_r__[pos__++];
            check_greater_or_equal(function__, "sigmasq_scale", sigmasq_scale, 0);
            current_statement_begin__ = 14;
            context__.validate_dims("data initialization", "a0_shape1", "double", context__.to_vec());
            a0_shape1 = double(0);
            vals_r__ = context__.vals_r("a0_shape1");
            pos__ = 0;
            a0_shape1 = vals_r__[pos__++];
            check_greater_or_equal(function__, "a0_shape1", a0_shape1, 0);
            current_statement_begin__ = 15;
            context__.validate_dims("data initialization", "a0_shape2", "double", context__.to_vec());
            a0_shape2 = double(0);
            vals_r__ = context__.vals_r("a0_shape2");
            pos__ = 0;
            a0_shape2 = vals_r__[pos__++];
            check_greater_or_equal(function__, "a0_shape2", a0_shape2, 0);
            current_statement_begin__ = 16;
            validate_non_negative_index("offset", "n", n);
            context__.validate_dims("data initialization", "offset", "vector_d", context__.to_vec(n));
            offset = Eigen::Matrix<double, Eigen::Dynamic, 1>(n);
            vals_r__ = context__.vals_r("offset");
            pos__ = 0;
            size_t offset_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < offset_j_1_max__; ++j_1__) {
                offset(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 17;
            validate_non_negative_index("offset0", "n0", n0);
            context__.validate_dims("data initialization", "offset0", "vector_d", context__.to_vec(n0));
            offset0 = Eigen::Matrix<double, Eigen::Dynamic, 1>(n0);
            vals_r__ = context__.vals_r("offset0");
            pos__ = 0;
            size_t offset0_j_1_max__ = n0;
            for (size_t j_1__ = 0; j_1__ < offset0_j_1_max__; ++j_1__) {
                offset0(j_1__) = vals_r__[pos__++];
            }
            // initialize transformed data variables
            current_statement_begin__ = 20;
            validate_non_negative_index("y_offset", "n", n);
            y_offset = Eigen::Matrix<double, Eigen::Dynamic, 1>(n);
            stan::math::fill(y_offset, DUMMY_VAR__);
            stan::math::assign(y_offset,subtract(y, offset));
            current_statement_begin__ = 21;
            validate_non_negative_index("y0_offset", "n0", n0);
            y0_offset = Eigen::Matrix<double, Eigen::Dynamic, 1>(n0);
            stan::math::fill(y0_offset, DUMMY_VAR__);
            stan::math::assign(y0_offset,subtract(y0, offset0));
            current_statement_begin__ = 22;
            validate_non_negative_index("hist_prec", "p", p);
            validate_non_negative_index("hist_prec", "p", p);
            hist_prec = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(p, p);
            stan::math::fill(hist_prec, DUMMY_VAR__);
            stan::math::assign(hist_prec,crossprod(X0));
            current_statement_begin__ = 23;
            validate_non_negative_index("hist_mle", "p", p);
            hist_mle = Eigen::Matrix<double, Eigen::Dynamic, 1>(p);
            stan::math::fill(hist_mle, DUMMY_VAR__);
            stan::math::assign(hist_mle,mdivide_left_spd(crossprod(X0), multiply(transpose(X0), y0_offset)));
            current_statement_begin__ = 24;
            validate_non_negative_index("prior_prec", "p", p);
            validate_non_negative_index("prior_prec", "p", p);
            prior_prec = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(p, p);
            stan::math::fill(prior_prec, DUMMY_VAR__);
            stan::math::assign(prior_prec,inverse_spd(cov_beta));
            current_statement_begin__ = 25;
            validate_non_negative_index("hist_prec_mle", "p", p);
            hist_prec_mle = Eigen::Matrix<double, Eigen::Dynamic, 1>(p);
            stan::math::fill(hist_prec_mle, DUMMY_VAR__);
            stan::math::assign(hist_prec_mle,multiply(hist_prec, hist_mle));
            current_statement_begin__ = 26;
            validate_non_negative_index("prior_prec_mean", "p", p);
            prior_prec_mean = Eigen::Matrix<double, Eigen::Dynamic, 1>(p);
            stan::math::fill(prior_prec_mean, DUMMY_VAR__);
            stan::math::assign(prior_prec_mean,multiply(prior_prec, mean_beta));
            current_statement_begin__ = 27;
            sumy0sq = double(0);
            stan::math::fill(sumy0sq, DUMMY_VAR__);
            stan::math::assign(sumy0sq,dot_self(y0_offset));
            current_statement_begin__ = 28;
            quad_b0 = double(0);
            stan::math::fill(quad_b0, DUMMY_VAR__);
            stan::math::assign(quad_b0,quad_form(prior_prec, mean_beta));
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 31;
            validate_non_negative_index("beta", "p", p);
            num_params_r__ += p;
            current_statement_begin__ = 32;
            num_params_r__ += 1;
            current_statement_begin__ = 33;
            num_params_r__ += 1;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_lm_npp() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 31;
        if (!(context__.contains_r("beta")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta");
        pos__ = 0U;
        validate_non_negative_index("beta", "p", p);
        context__.validate_dims("parameter initialization", "beta", "vector_d", context__.to_vec(p));
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta(p);
        size_t beta_j_1_max__ = p;
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            beta(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(beta);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 32;
        if (!(context__.contains_r("sigmasq")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigmasq missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigmasq");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "sigmasq", "double", context__.to_vec());
        double sigmasq(0);
        sigmasq = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, sigmasq);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigmasq: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 33;
        if (!(context__.contains_r("a0")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable a0 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("a0");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "a0", "double", context__.to_vec());
        double a0(0);
        a0 = vals_r__[pos__++];
        try {
            writer__.scalar_lub_unconstrain(0, 1, a0);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable a0: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 31;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> beta;
            (void) beta;  // dummy to suppress unused var warning
            if (jacobian__)
                beta = in__.vector_constrain(p, lp__);
            else
                beta = in__.vector_constrain(p);
            current_statement_begin__ = 32;
            local_scalar_t__ sigmasq;
            (void) sigmasq;  // dummy to suppress unused var warning
            if (jacobian__)
                sigmasq = in__.scalar_lb_constrain(0, lp__);
            else
                sigmasq = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 33;
            local_scalar_t__ a0;
            (void) a0;  // dummy to suppress unused var warning
            if (jacobian__)
                a0 = in__.scalar_lub_constrain(0, 1, lp__);
            else
                a0 = in__.scalar_lub_constrain(0, 1);
            // model body
            {
            current_statement_begin__ = 38;
            validate_non_negative_index("prec_a0", "p", p);
            validate_non_negative_index("prec_a0", "p", p);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> prec_a0(p, p);
            stan::math::initialize(prec_a0, DUMMY_VAR__);
            stan::math::fill(prec_a0, DUMMY_VAR__);
            stan::math::assign(prec_a0,add(multiply(a0, hist_prec), prior_prec));
            current_statement_begin__ = 40;
            validate_non_negative_index("mean_a0", "p", p);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> mean_a0(p);
            stan::math::initialize(mean_a0, DUMMY_VAR__);
            stan::math::fill(mean_a0, DUMMY_VAR__);
            stan::math::assign(mean_a0,mdivide_left_spd(prec_a0, add(multiply(a0, hist_prec_mle), prior_prec_mean)));
            current_statement_begin__ = 42;
            local_scalar_t__ shape_a0(DUMMY_VAR__);
            (void) shape_a0;  // dummy to suppress unused var warning
            stan::math::initialize(shape_a0, DUMMY_VAR__);
            stan::math::fill(shape_a0, DUMMY_VAR__);
            stan::math::assign(shape_a0,(sigmasq_shape + ((0.5 * a0) * n0)));
            current_statement_begin__ = 44;
            local_scalar_t__ scale_a0(DUMMY_VAR__);
            (void) scale_a0;  // dummy to suppress unused var warning
            stan::math::initialize(scale_a0, DUMMY_VAR__);
            stan::math::fill(scale_a0, DUMMY_VAR__);
            stan::math::assign(scale_a0,(sigmasq_scale + (0.5 * (((a0 * sumy0sq) + quad_b0) - quad_form(prec_a0, mean_a0)))));
            current_statement_begin__ = 48;
            lp_accum__.add(normal_id_glm_lpdf<propto__>(y_offset, X, 0.0, beta, stan::math::sqrt(sigmasq)));
            current_statement_begin__ = 51;
            lp_accum__.add(inv_gamma_log(sigmasq, shape_a0, scale_a0));
            current_statement_begin__ = 52;
            lp_accum__.add(multi_normal_prec_log(beta, mean_a0, multiply(prec_a0, inv(sigmasq))));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("beta");
        names__.push_back("sigmasq");
        names__.push_back("a0");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(p);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_lm_npp_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta = in__.vector_constrain(p);
        size_t beta_j_1_max__ = p;
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            vars__.push_back(beta(j_1__));
        }
        double sigmasq = in__.scalar_lb_constrain(0);
        vars__.push_back(sigmasq);
        double a0 = in__.scalar_lub_constrain(0, 1);
        vars__.push_back(a0);
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            if (!include_gqs__ && !include_tparams__) return;
            if (!include_gqs__) return;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_lm_npp";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t beta_j_1_max__ = p;
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigmasq";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "a0";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t beta_j_1_max__ = p;
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigmasq";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "a0";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
    }
}; // model
}  // namespace
typedef model_lm_npp_namespace::model_lm_npp stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
